# -*- coding: utf-8 -*-
"""modelo_de_regressão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KHfCcoEfbXqtdmNdDLAeSBkPT0Fdr4Gx
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

diabetes_X = diabetes_X[:, np.newaxis, 2]

diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]

diabetes_y_train = diabetes_y[:-20]
diabetes_y_test = diabetes_y[-20:]

# Criar objeto de regressão linear
regr = linear_model.LinearRegression()

# Treine o modelo usando os conjuntos de treinamento
regr.fit(diabetes_X_train, diabetes_y_train)

# Faça previsões usando o conjunto de testes
diabetes_y_pred = regr.predict(diabetes_X_test)

# Os coeficientes
print("Coefficients: \n", regr.coef_)
# O erro quadrático médio
print("Mean squared error: %.2f" % mean_squared_error(diabetes_y_test, diabetes_y_pred))
# O coeficiente de determinação: 1 é a previsão perfeita
print("Coefficient of determination: %.2f" % r2_score(diabetes_y_test, diabetes_y_pred))

# Saídas de plotagem
plt.scatter(diabetes_X_test, diabetes_y_test, color="black")
plt.plot(diabetes_X_test, diabetes_y_pred, color="blue", linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()